name: robotic_gambit
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.25.4  # Updated to the latest version as per your instruction
  cloud_firestore: ^4.15.4  # Updated to the latest version as per your instruction
  firebase_auth: ^4.17.4
  js: ^0.6.3
  url_launcher: ^6.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1  # Updated to the latest version


flutter:
  uses-material-design: true

  assets:
    - assets/logo_gambit.png
