name: robotic_gambit
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  cupertino_icons: ^1.0.2
  firebase_core: ^2.25.4  # Updated to the latest version as per your instruction
  cloud_firestore: ^4.15.4  # Updated to the latest version as per your instruction
  firebase_auth: ^4.17.4
  js: ^0.6.3
  url_launcher: ^6.0.12
  intl: ^0.17.0
  chess: ^0.7.0
  flutter_chess_board: ^1.0.1
  audioplayers: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

  # flutter_test:
  #   sdk: flutter
  # flutter_lints: ^3.0.1  # Updated to the latest version


flutter:
  uses-material-design: true

  assets:
    - assets/logo_gambit.png
    - assets/styled_chess_board.png
    - assets/sounds/game-end.mp3
    - assets/sounds/game-start.mp3
    - assets/sounds/move-self.mp3